spring:
  application:
    name: experiencias-soria-backend

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:soria}?useSSL=${MYSQL_USE_SSL:false}&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}

# Propiedades de la app
app:
  jwt-secret: ${JWT_SECRET:estaesunaclavesuperseguraylargaparafirmartokensjwt}
  jwt-expiration: ${JWT_EXPIRATION:3600000} # 1 hora en milisegundos
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://172.20.10.2:8081,http://172.20.10.2:8082}

